package DL2::Schema::Item;

use strict;
use warnings;

use base 'DBIx::Class';

__PACKAGE__->load_components("Core");
__PACKAGE__->table("ZABSTRACTAMAZONATTRIBUTESHOLDER");
__PACKAGE__->add_columns(
  "zminimumplayers",
  {
    data_type => "INTEGER",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zloan",
  {
    data_type => "INTEGER",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "znumberofmedia",
  {
    data_type => "INTEGER",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zminutes",
  {
    data_type => "INTEGER",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zuserreview",
  {
    data_type => "INTEGER",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zamazonpercountrycacheentry1",
  {
    data_type => "INTEGER",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zusersynopsis",
  {
    data_type => "INTEGER",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "z29_rootshelf",
  {
    data_type => "INTEGER",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "z_pk",
  {
    data_type => "INTEGER",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zrootshelf",
  {
    data_type => "INTEGER",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zissigned",
  {
    data_type => "INTEGER",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zhasexperienced",
  {
    data_type => "INTEGER",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zpages",
  {
    data_type => "INTEGER",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zused",
  {
    data_type => "INTEGER",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "z_opt",
  {
    data_type => "INTEGER",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zrare",
  {
    data_type => "INTEGER",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zprivatecollection",
  {
    data_type => "INTEGER",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zamazonpercountrycacheentry",
  {
    data_type => "INTEGER",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zmediadatafetcher",
  {
    data_type => "INTEGER",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zorder",
  {
    data_type => "INTEGER",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "znumberinseries",
  {
    data_type => "INTEGER",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "ztotalreviewscount",
  {
    data_type => "INTEGER",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zhaseverbeenfetched",
  {
    data_type => "INTEGER",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "z_ent",
  {
    data_type => "INTEGER",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zcoverimage",
  {
    data_type => "INTEGER",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zmaximumplayers",
  {
    data_type => "INTEGER",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zlastlookupdate",
  {
    data_type => "TIMESTAMP",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zpublishdate",
  {
    data_type => "TIMESTAMP",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zboxheightininches",
  {
    data_type => "FLOAT",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zboxlengthininches",
  {
    data_type => "FLOAT",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "ztheatricaldate",
  {
    data_type => "TIMESTAMP",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "znetrating",
  {
    data_type => "FLOAT",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zlastmodificationdate",
  {
    data_type => "TIMESTAMP",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zboxweightinpounds",
  {
    data_type => "FLOAT",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zboxwidthininches",
  {
    data_type => "FLOAT",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zlastreviewslookupdate",
  {
    data_type => "TIMESTAMP",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zlastsynopseslookupdate",
  {
    data_type => "TIMESTAMP",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zlastpriceslookupdate",
  {
    data_type => "TIMESTAMP",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zlastrecommendationslookupdate",
  {
    data_type => "TIMESTAMP",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zpurchasedate",
  {
    data_type => "TIMESTAMP",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zcreationdate",
  {
    data_type => "TIMESTAMP",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zrating",
  {
    data_type => "FLOAT",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zserialnumber",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zcreatorscompositestring",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zgenrescompositestring",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zseriessingularstring",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zplatformscompositestring",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zdeweydecimal",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zlanguagescompositestring",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zuuidstring",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zasin",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "ztitle",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zsubtitle",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zprice",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zconductorscompositestring",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zaudiencerecommendedagesingularstring",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zfulltitle",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zactorscompositestring",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zean",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zillustratorscompositestring",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zownersingularstring",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zassociatedurl",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zlocationsingularstring",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "ztrackscompositestring",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zcurrentvalue",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zconditionsingularstring",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "znotes",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zforeignuuidstring",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zfeaturescompositestring",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zitunesabstractcollectionkey",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zscreenwriterscompositestring",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zkey",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zcountrycode",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zisbn",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zcinematographerscompositestring",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "ztype",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zcomposerscompositestring",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zpublisherscompositestring",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zbuyprice",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zlibraryofcongresscallnumber",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zformatsingularstring",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
  "zeditionscompositestring",
  {
    data_type => "VARCHAR",
    default_value => undef,
    is_nullable => 1,
    size => undef,
  },
);
__PACKAGE__->set_primary_key("z_pk");


# Created by DBIx::Class::Schema::Loader v0.04006 @ 2009-12-02 17:45:28
# DO NOT MODIFY THIS OR ANYTHING ABOVE! md5sum:Z9886Sk1zRcE8kXE6fHcyQ


# You can replace this text with custom content, and it will be preserved on regeneration
1;
